import { CrawlResult, CrawledRule, BestPracticeRule, AntiPatternRule, SecurityAdvisoryRule } from '../types';

/**
 * Formats crawl results as SQL INSERT statements matching the DB schema.
 *
 * Routes rules to the correct table:
 * - best_practice → best_practices
 * - anti_pattern  → anti_patterns
 * - security      → security_advisories
 */
export class SQLFormatter {
  /**
   * Format crawl result as SQL
   */
  format(result: CrawlResult): string {
    const lines: string[] = [];

    lines.push('-- Generated by Context Guardian Data Crawler');
    lines.push(`-- Library: ${result.library}`);
    lines.push(`-- Crawled at: ${result.crawledAt}`);
    lines.push(`-- Total rules: ${result.rules.length}`);
    lines.push('');

    // Insert library first
    lines.push('-- Insert library');
    lines.push(this.formatLibraryInsert(result));
    lines.push('');

    // Group rules by type
    const bestPractices = result.rules.filter(r => r.type === 'best_practice');
    const antiPatterns = result.rules.filter(r => r.type === 'anti_pattern');
    const securityAdvisories = result.rules.filter(r => r.type === 'security');

    if (bestPractices.length > 0) {
      lines.push(`-- Best practices (${bestPractices.length})`);
      for (const rule of bestPractices) {
        lines.push(this.formatBestPracticeInsert(rule.data as BestPracticeRule, result));
      }
      lines.push('');
    }

    if (antiPatterns.length > 0) {
      lines.push(`-- Anti-patterns (${antiPatterns.length})`);
      for (const rule of antiPatterns) {
        lines.push(this.formatAntiPatternInsert(rule.data as AntiPatternRule, result));
      }
      lines.push('');
    }

    if (securityAdvisories.length > 0) {
      lines.push(`-- Security advisories (${securityAdvisories.length})`);
      for (const rule of securityAdvisories) {
        lines.push(this.formatSecurityAdvisoryInsert(rule.data as SecurityAdvisoryRule, result));
      }
      lines.push('');
    }

    return lines.join('\n');
  }

  /**
   * Format library INSERT — ON CONFLICT (name) matches the UNIQUE constraint
   */
  private formatLibraryInsert(result: CrawlResult): string {
    return `INSERT INTO libraries (name, ecosystem, official_docs_url, created_at, updated_at)
VALUES (
  '${this.escape(result.library)}',
  '${this.escape(result.ecosystem)}',
  '${this.escape(result.sourceUrls[0] || '')}',
  NOW(),
  NOW()
)
ON CONFLICT (name) DO UPDATE SET
  updated_at = NOW();`;
  }

  /**
   * Format best_practices INSERT — uses version_range, not min/max_version
   */
  private formatBestPracticeInsert(rule: BestPracticeRule, result: CrawlResult): string {
    return `
INSERT INTO best_practices (
  library_id, title, description, category, severity,
  version_range, code_example, source_url, created_at, updated_at
)
VALUES (
  (SELECT id FROM libraries WHERE name = '${this.escape(result.library)}' LIMIT 1),
  '${this.escape(rule.title)}',
  '${this.escape(rule.description)}',
  '${this.escape(rule.category)}',
  '${this.escape(rule.severity)}',
  '${this.escape(rule.version_range)}',
  ${rule.code_example ? `'${this.escape(rule.code_example)}'` : 'NULL'},
  '${this.escape(rule.source_url)}',
  NOW(),
  NOW()
);`;
  }

  /**
   * Format anti_patterns INSERT — separate table with pattern_name, why_bad, better_approach
   */
  private formatAntiPatternInsert(rule: AntiPatternRule, result: CrawlResult): string {
    return `
INSERT INTO anti_patterns (
  library_id, pattern_name, description, why_bad, better_approach,
  severity, version_range, code_example_bad, code_example_good, source_url,
  created_at, updated_at
)
VALUES (
  (SELECT id FROM libraries WHERE name = '${this.escape(result.library)}' LIMIT 1),
  '${this.escape(rule.pattern_name)}',
  '${this.escape(rule.description)}',
  '${this.escape(rule.why_bad)}',
  '${this.escape(rule.better_approach)}',
  '${this.escape(rule.severity)}',
  ${rule.version_range ? `'${this.escape(rule.version_range)}'` : 'NULL'},
  ${rule.code_example_bad ? `'${this.escape(rule.code_example_bad)}'` : 'NULL'},
  ${rule.code_example_good ? `'${this.escape(rule.code_example_good)}'` : 'NULL'},
  ${rule.source_url ? `'${this.escape(rule.source_url)}'` : 'NULL'},
  NOW(),
  NOW()
);`;
  }

  /**
   * Format security_advisories INSERT
   */
  private formatSecurityAdvisoryInsert(rule: SecurityAdvisoryRule, result: CrawlResult): string {
    return `
INSERT INTO security_advisories (
  library_id, cve_id, title, description, severity,
  affected_versions, fixed_in_version, source_url, published_at, created_at
)
VALUES (
  (SELECT id FROM libraries WHERE name = '${this.escape(result.library)}' LIMIT 1),
  ${rule.cve_id ? `'${this.escape(rule.cve_id)}'` : 'NULL'},
  '${this.escape(rule.title)}',
  '${this.escape(rule.description)}',
  '${this.escape(rule.severity)}',
  '${this.escape(rule.affected_versions)}',
  ${rule.fixed_in_version ? `'${this.escape(rule.fixed_in_version)}'` : 'NULL'},
  '${this.escape(rule.source_url)}',
  ${rule.published_at ? `'${this.escape(rule.published_at)}'` : 'NULL'},
  NOW()
);`;
  }

  /**
   * Escape SQL string values
   */
  private escape(str: string): string {
    return str
      .replace(/\\/g, '\\\\')
      .replace(/'/g, "''")
      .replace(/\0/g, '')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '\\r');
  }
}
